stages:
    - build
    - deploy
    
build-rpi:
    stage: build
    tags:
        - rpi
    script:
        - make build-rpi
        
deploy-rpi:
    stage: deploy
    tags:
        - rpi
    script:
        - make push-rpi
        
